import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/layouts/Navbar";
import Footer from "./_components/layouts/Footer";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cybertech | E-commere store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0"
        />
      </head>
      <body className={`${inter.variable} antialiased bg-gray-900`}>
        {children}
        <Toaster
          position="top-center"
          reverseOrder={false}
          gutter={8} // Space between toasts
          containerClassName=""
          containerStyle={{}}
          toastOptions={{
            // Default options for all toasts
            duration: 3000,
            style: {
              background: "#222",
              color: "#eee",
            },
            success: {
              iconTheme: {
                primary: "green",
                secondary: "white",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
